language: julia

julia:
  - 1.1
  - 1.2
  - 1.3
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
  - julia: nightly

codecov: true

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
